"""Conversation history management for Gemini chat sessions.

This module provides conversation history management with proper message
formatting and part extraction for Google GenAI types.
"""

from typing import Any

from google.genai import types

from config.settings import settings
from utils.logger import get_logger

logger = get_logger("ConversationManager", settings.LOG_LEVEL)


class ConversationManager:
    """Manager for conversation history and message formatting.

    This class handles all conversation history operations including:
    - Adding user and model messages
    - Adding function calls and responses
    - Extracting text and function calls from parts
    - Managing conversation history lifecycle

    Attributes:
        conversation_history: List of Content objects representing the conversation
    """

    def __init__(self):
        """Initialize conversation manager with empty history."""
        self.conversation_history: list[types.Content] = []

    def add_user_message(self, text: str) -> None:
        """Add user message to conversation history.

        Args:
            text: User message text

        Example:
            >>> manager = ConversationManager()
            >>> manager.add_user_message("Hello")
            >>> len(manager.conversation_history)
            1
        """
        self.conversation_history.append(
            types.Content(role="user", parts=[types.Part(text=text)])
        )
        logger.debug(f"Added user message: {text[:50]}...")

    def add_model_message(self, text: str) -> None:
        """Add model message to conversation history.

        Args:
            text: Model response text

        Example:
            >>> manager = ConversationManager()
            >>> manager.add_model_message("Hi there!")
            >>> manager.conversation_history[0].role
            'model'
        """
        self.conversation_history.append(
            types.Content(role="model", parts=[types.Part(text=text)])
        )
        logger.debug(f"Added model message: {text[:50]}...")

    def add_function_call(self, parts: list[types.Part]) -> None:
        """Add function call parts to history as model response.

        Function calls are generated by the model and should be tracked
        as model responses before executing them.

        Args:
            parts: List of parts containing function_call objects

        Example:
            >>> manager = ConversationManager()
            >>> parts = [types.Part(function_call=...)]
            >>> manager.add_function_call(parts)
        """
        self.conversation_history.append(
            types.Content(role="model", parts=parts)
        )
        logger.debug(f"Added function call with {len(parts)} parts")

    def add_function_response(self, parts: list[types.Part]) -> None:
        """Add function response parts to history as user message.

        Per Gemini's official pattern, function responses are added
        as "user" role messages.

        Args:
            parts: List of parts containing function_response objects

        Example:
            >>> manager = ConversationManager()
            >>> parts = [types.Part(function_response=...)]
            >>> manager.add_function_response(parts)
        """
        self.conversation_history.append(
            types.Content(role="user", parts=parts)
        )
        logger.debug(f"Added function response with {len(parts)} parts")

    def extract_text_from_parts(self, parts: list[types.Part] | None) -> str | None:
        """Extract text content from response parts.

        Args:
            parts: Response parts that may contain text

        Returns:
            Concatenated text from all text parts, or None if no text found

        Example:
            >>> manager = ConversationManager()
            >>> parts = [types.Part(text="Hello"), types.Part(text="World")]
            >>> manager.extract_text_from_parts(parts)
            'Hello World'
        """
        if parts is None:
            logger.warning("Parts is None - cannot extract text")
            return None

        text_parts = [
            part.text
            for part in parts
            if hasattr(part, "text") and part.text
        ]

        if not text_parts:
            return None

        combined_text = " ".join(text_parts)
        logger.debug(f"Extracted text: {combined_text[:50]}...")
        return combined_text

    def extract_function_calls(self, parts: list[types.Part] | None) -> list[Any]:
        """Extract function calls from response parts.

        Args:
            parts: Response parts that may contain function calls

        Returns:
            List of function_call objects

        Example:
            >>> manager = ConversationManager()
            >>> parts = [types.Part(function_call=fc)]
            >>> calls = manager.extract_function_calls(parts)
            >>> len(calls)
            1
        """
        if parts is None:
            logger.warning("Parts is None - cannot extract function calls")
            return []

        function_calls = [
            part.function_call
            for part in parts
            if hasattr(part, "function_call") and part.function_call
        ]

        if function_calls:
            logger.debug(f"Extracted {len(function_calls)} function calls")

        return function_calls

    def get_history(self) -> list[types.Content]:
        """Get current conversation history.

        Returns:
            List of Content objects representing the conversation

        Example:
            >>> manager = ConversationManager()
            >>> manager.add_user_message("Hi")
            >>> history = manager.get_history()
            >>> len(history)
            1
        """
        return self.conversation_history

    def clear(self) -> None:
        """Clear conversation history.

        Useful for starting a new conversation session.

        Example:
            >>> manager = ConversationManager()
            >>> manager.add_user_message("Test")
            >>> manager.clear()
            >>> len(manager.conversation_history)
            0
        """
        count = len(self.conversation_history)
        self.conversation_history.clear()
        logger.debug(f"Cleared conversation history ({count} messages)")

    def get_last_user_message(self) -> str | None:
        """Get the last user message text.

        Returns:
            Last user message text, or None if no user messages

        Example:
            >>> manager = ConversationManager()
            >>> manager.add_user_message("Hello")
            >>> manager.get_last_user_message()
            'Hello'
        """
        for content in reversed(self.conversation_history):
            if content.role == "user":
                # Extract text from first text part
                for part in content.parts:
                    if hasattr(part, "text") and part.text:
                        return part.text
        return None

    def get_function_responses_for_query(
        self, user_query: str, max_lookback: int = 10
    ) -> list[dict[str, Any]]:
        """Get function responses related to a user query.

        Searches recent conversation history for function responses
        that match the given user query.

        Args:
            user_query: User query to match against
            max_lookback: Maximum number of messages to look back

        Returns:
            List of function response data dictionaries

        Example:
            >>> manager = ConversationManager()
            >>> responses = manager.get_function_responses_for_query("search laptops")
            >>> len(responses)
            0
        """
        function_responses = []

        # Look for function_response parts in recent history
        for content in reversed(self.conversation_history[-max_lookback:]):
            if content.role == "user":  # Function responses are "user" role
                for part in content.parts:
                    if hasattr(part, "function_response") and part.function_response:
                        response_data = part.function_response.response
                        if isinstance(response_data, dict):
                            function_responses.append(response_data)

        if function_responses:
            logger.debug(
                f"Found {len(function_responses)} function responses for query: {user_query[:30]}..."
            )

        return function_responses

    def get_message_count(self) -> int:
        """Get total number of messages in history.

        Returns:
            Number of messages (Content objects) in history

        Example:
            >>> manager = ConversationManager()
            >>> manager.add_user_message("Hi")
            >>> manager.get_message_count()
            1
        """
        return len(self.conversation_history)
