"""Response processing with validation and debug info aggregation.

This module handles all post-generation response processing including:
- SKU validation (anti-hallucination)
- Debug info aggregation
- JSON artifact cleaning
- Fallback pattern detection
"""

from client_mcp.config.settings import settings
from client_mcp.core.debug_formatter import DebugFormatter
from client_mcp.core.response_validator import ResponseValidator
from client_mcp.core.tool_executor import ToolExecutor
from client_mcp.utils.logger import get_logger

# Observability imports (OPCIÓN 8)
try:
    from email_service.observability.metrics import get_metrics_collector
    from email_service.observability.structured_logger import get_structured_logger
    OBSERVABILITY_AVAILABLE = True
except ImportError:
    OBSERVABILITY_AVAILABLE = False

logger = get_logger("ResponseProcessor", settings.LOG_LEVEL)


class ResponseProcessor:
    """Processor for model responses with validation and debug info.

    This class handles all response post-processing including:
    - Anti-hallucination SKU validation
    - Debug information aggregation
    - Fallback pattern detection
    - JSON artifact cleaning

    Attributes:
        response_validator: Validator for SKU checking
        debug_formatter: Formatter for debug information
        tool_executor: Optional tool executor for metrics
    """

    def __init__(
        self,
        response_validator: ResponseValidator,
        debug_formatter: DebugFormatter,
        tool_executor: ToolExecutor | None = None,
    ):
        """Initialize response processor.

        Args:
            response_validator: Validator instance for SKU checking
            debug_formatter: Formatter instance for debug info
            tool_executor: Optional tool executor for metrics access
        """
        # Initialize observability (OPCIÓN 8)
        if OBSERVABILITY_AVAILABLE:
            self.structured_logger = get_structured_logger("response_processor")
            self.metrics = get_metrics_collector()
        else:
            self.structured_logger = None
            self.metrics = None

        self.response_validator = response_validator
        self.debug_formatter = debug_formatter
        self.tool_executor = tool_executor

    async def process_text_response(self, text: str, user_query: str) -> str:
        """Process text response with validation and debug info.

        Args:
            text: Raw text response from model
            user_query: Original user query for context

        Returns:
            Processed and validated response with debug info
        """
        # Track response processing with metrics (OPCIÓN 8)
        try:
            if self.metrics:
                latency_ctx = self.metrics.record_latency_async(
                    "response_processing_latency"
                )
            else:
                latency_ctx = None

            if latency_ctx:
                await latency_ctx.__aenter__()

            if self.metrics:
                self.metrics.increment_counter("response_processing_attempts", 1)

            # ✅ ANTI-HALLUCINATION: Validate SKUs in response
            validated_text = self.response_validator.validate_response_skus(text, user_query)

            if validated_text is not None:
                if self.metrics:
                    self.metrics.increment_counter("response_validation_success", 1)
            else:
                if self.metrics:
                    self.metrics.increment_counter("response_validation_failure_invalid_skus", 1)

            # ✅ Remove any DEBUG INFO generated by Gemini (hallucination)
            if validated_text:
                validated_text = ResponseValidator.remove_generated_debug_info(validated_text)

            if validated_text is None:
                # Response contained invalid SKUs - regenerate with strict constraint
                logger.warning("⚠️ Response contained invalid SKUs. Regenerating...")
                if self.metrics:
                    self.metrics.increment_counter("response_regeneration_triggered", 1)
                if self.structured_logger:
                    self.structured_logger.warning("Response regeneration triggered due to invalid SKUs")

                regenerated = await self.response_validator.regenerate_without_hallucinations(user_query)

                if self.metrics:
                    self.metrics.increment_counter("response_regeneration_completed", 1)

                return ResponseValidator.clean_json_artifacts(regenerated)

            # Add debug info for tool executions
            validated_text = self._add_debug_info(validated_text, user_query)

            # Clean JSON artifacts before returning
            cleaned_text = ResponseValidator.clean_json_artifacts(validated_text)

            if self.structured_logger:
                self.structured_logger.info("Response processed successfully")

            return cleaned_text

        except Exception as e:
            if self.metrics:
                self.metrics.increment_counter("response_processing_failure", 1)
                self.metrics.increment_counter(f"response_error_{type(e).__name__}", 1)
            if self.structured_logger:
                self.structured_logger.exception("Response processing failed")
            raise

        finally:
            if latency_ctx:
                await latency_ctx.__aexit__(None, None, None)

    def _add_debug_info(self, text: str, user_query: str) -> str:
        """Add debug information for tool executions.

        Args:
            text: Response text to augment
            user_query: User query to match metrics

        Returns:
            Text with debug info appended
        """
        if not self.tool_executor:
            return text

        # Access private _metrics list (no public getter available)
        all_metrics = self.tool_executor.tracker.collector._metrics
        matching_metrics = [m for m in all_metrics if m.user_query == user_query]

        # Detect fallback pattern: one tool with 0 results, another with results
        if len(matching_metrics) == 2:
            first, second = matching_metrics[0], matching_metrics[1]
            # Check if this is a fallback scenario (order-independent)
            if (
                first.success
                and second.success
                and (
                    (first.result_size == 0 and second.result_size > 0)
                    or (second.result_size == 0 and first.result_size > 0)
                )
            ):
                # Determine which is primary (0 results) and which is fallback (has results)
                primary = first if first.result_size == 0 else second
                fallback_tool = second if first.result_size == 0 else first

                # Combine both metrics into single DEBUG INFO
                if self.debug_formatter.should_show_fallback(primary, fallback_tool):
                    debug_info = self.debug_formatter.format_fallback_debug_info(primary, fallback_tool)
                    text += debug_info

                # Skip normal processing since we handled fallback
                matching_metrics = []

        # Normal processing for non-fallback or single metrics
        for metric in matching_metrics:
            # Only add if not already shown
            if self.debug_formatter.should_show_metric(metric):
                debug_info = self.debug_formatter.format_debug_info(metric)
                text += debug_info

        return text
