-- ============================================================================
-- DEMO_SESSIONS TABLE - Session metadata and state tracking
-- ============================================================================
-- Metadata sobre sesiones de demostración
-- Permite resumir sesiones, rastrear actividad, y recolectar analytics

CREATE TABLE IF NOT EXISTS :SCHEMA_NAME.demo_sessions (
    -- Primary key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- User identification
    user_id VARCHAR(255),
        -- Authenticated user ID (if logged in)
        -- NULL for anonymous users

    session_id VARCHAR(255),
        -- Session token (generated by client)
        -- Used to group requests from same browser/device

    -- Network information
    ip_address INET,
        -- Client IP address at session creation time
        -- Used to detect VPN/proxy changes mid-session

    user_agent TEXT,
        -- HTTP User-Agent at session creation (for consistency checks)

    -- Language and locale
    language VARCHAR(10) NOT NULL DEFAULT 'es',
        -- Language preference (es | en | other)
        -- Used to determine prompt language

    -- Usage statistics (denormalized for faster analytics)
    total_tokens_used INTEGER NOT NULL DEFAULT 0,
        -- Cumulative tokens used in this session
        -- Updated after each request

    total_requests INTEGER NOT NULL DEFAULT 0,
        -- Number of API requests in this session
        -- Used to track engagement

    -- Activity tracking
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        -- When session was created (session start time)

    last_activity_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        -- Last time user made a request (for session timeout)
        -- Updated on every request

    -- Constraints
    CONSTRAINT chk_demo_sessions_language CHECK (
        language IN ('es', 'en')
    ),
    CONSTRAINT chk_demo_sessions_tokens CHECK (
        total_tokens_used >= 0
    ),
    CONSTRAINT chk_demo_sessions_requests CHECK (
        total_requests >= 0
    ),
    CONSTRAINT chk_demo_sessions_timeline CHECK (
        last_activity_at >= created_at
    )
);

-- ============================================================================
-- INDEXES - Optimized for session lookups and analytics
-- ============================================================================

-- Primary lookup: get session by session_id
CREATE INDEX IF NOT EXISTS idx_demo_sessions_session_id
    ON :SCHEMA_NAME.demo_sessions(session_id)
    WHERE session_id IS NOT NULL;

-- User lookup: get all sessions for authenticated user
CREATE INDEX IF NOT EXISTS idx_demo_sessions_user_id
    ON :SCHEMA_NAME.demo_sessions(user_id)
    WHERE user_id IS NOT NULL;

-- Activity tracking: find active sessions (for timeout detection)
CREATE INDEX IF NOT EXISTS idx_demo_sessions_last_activity
    ON :SCHEMA_NAME.demo_sessions(last_activity_at DESC);

-- Analytics: sessions by language
CREATE INDEX IF NOT EXISTS idx_demo_sessions_language
    ON :SCHEMA_NAME.demo_sessions(language, created_at DESC);

-- Analytics: high-usage sessions
CREATE INDEX IF NOT EXISTS idx_demo_sessions_token_usage
    ON :SCHEMA_NAME.demo_sessions(total_tokens_used DESC)
    WHERE total_tokens_used > 1000;

-- Network analysis: sessions from IP
CREATE INDEX IF NOT EXISTS idx_demo_sessions_ip_address
    ON :SCHEMA_NAME.demo_sessions(ip_address, created_at DESC);

-- Timeline: new sessions (time-series analysis)
CREATE INDEX IF NOT EXISTS idx_demo_sessions_created_at
    ON :SCHEMA_NAME.demo_sessions(created_at DESC);

-- ============================================================================
-- PERMISSIONS
-- ============================================================================
GRANT SELECT, INSERT, UPDATE ON :SCHEMA_NAME.demo_sessions TO mcp_user;
GRANT USAGE, SELECT ON SEQUENCE :SCHEMA_NAME.demo_sessions_id_seq TO mcp_user;

-- Restrict DELETE to admin only (preserve history for analytics)
-- GRANT DELETE is NOT granted to mcp_user

-- ============================================================================
-- VERIFICATION
-- ============================================================================
DO $$
BEGIN
    RAISE NOTICE '✅ Demo sessions table created';
    RAISE NOTICE '   - Session metadata and state tracking';
    RAISE NOTICE '   - Denormalized statistics (tokens, requests)';
    RAISE NOTICE '   - Activity timeline for engagement tracking';
    RAISE NOTICE '   - Network and language analytics';
END $$;
